import React, { useState, useEffect } from 'react';
import {
  FileText,
  Download, 
  Brain,
  Plus,
  History,
  Search,
  Filter,
  Trash2,
  Edit,
  Sliders,
  BarChart3,
  PieChart,
  Target,
  Globe,
  Zap,
  CheckCircle
} from 'lucide-react';
import { sampleAIReports, sampleAIReportTemplates } from '../data/intelligenceData';

interface ProfileData {
  fullName: string;
  email: string;
  phone: string;
  linkedinProfile: string;
  country: string;
  language: string;
  currentOccupation: string;
  yearsExperience: string;
  entrepreneurialExperience: string;
  industryExpertise: string;
  marketExpertise: string;
  keySkills: string;
  company: string;
  companyLinkedin: string;
  companyType: string;
  industryFocus: string;
  origin: string;
  companySize: string;
  portfolioSize: string;
  headquarters: string;
  operatingMarkets: string;
  targetClients: string;
  keyCapabilities: string;
}

interface AIReportDevelopmentProps {
  isAICompanionOpen: boolean;
  aiCompanionWidth: number;
  toggleAICompanion: () => void;
  selectedRole: 'founder' | 'investor' | 'expert';
  profileData: ProfileData;
}

function AIReportDevelopment({
  isAICompanionOpen,
  aiCompanionWidth,
  toggleAICompanion,
  selectedRole,
  profileData
}: AIReportDevelopmentProps) {
  const [activeAIReportTab, setActiveAIReportTab] = useState('generate-report');
  const [reportParameters, setReportParameters] = useState({
    industry: '',
    market: '',
    topic: '',
    purpose: '',
    researchElements: '',
    dataVisualization: 'charts',
    analysisDepth: 'standard',
    includePredictions: true,
    includeRecommendations: true,
    customSections: [] as string[],
    customSection: ''
  });
  const [generatedReportContent, setGeneratedReportContent] = useState('');
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);

  // Scroll to top when component mounts
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const aiReportsTabs = [
    { id: 'generate-report', label: 'Generate AI Report', icon: Plus },
    { id: 'reports-history', label: 'Reports history', icon: History }
  ];

  const handleParameterChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setReportParameters(prev => ({ ...prev, [name]: value }));
  };

  const handleCheckboxChange = (name: string, checked: boolean) => {
    setReportParameters(prev => ({ ...prev, [name]: checked }));
  };

  const handleAddCustomSection = () => {
    if (reportParameters.customSection.trim()) {
      setReportParameters(prev => ({
        ...prev,
        customSections: [...prev.customSections, prev.customSection.trim()],
        customSection: ''
      }));
    }
  };

  const handleRemoveCustomSection = (section: string) => {
    setReportParameters(prev => ({
      ...prev,
      customSections: prev.customSections.filter(s => s !== section)
    }));
  };

  const handleGenerateReport = () => {
    // Simulate AI report generation
    const newReportContent = `## AI Generated Report: ${reportParameters.topic} in ${reportParameters.market} (${reportParameters.industry})

### Introduction
This report provides a comprehensive analysis of the ${reportParameters.topic} within the ${reportParameters.industry} sector in the ${reportParameters.market} market, tailored for ${reportParameters.purpose}.

### Key Findings
*   **Market Overview:** The ${reportParameters.market} ${reportParameters.industry} market is experiencing significant growth, driven by [specific factors].
*   **Competitive Landscape:** Key players include [Company A], [Company B], and [Company C], with emerging startups [Startup X] and [Startup Y] disrupting the space.
*   **Trends & Opportunities:** Emerging trends such as [Trend 1] and [Trend 2] present unique opportunities for innovation and investment.
*   **Challenges & Risks:** Potential challenges include [Challenge 1] and [Challenge 2], which require strategic mitigation.

### Detailed Analysis
[Detailed analysis based on research elements: ${reportParameters.researchElements}. This section would typically include data visualizations, in-depth market segmentation, and stakeholder analysis.]

### Recommendations
Based on the analysis, we recommend [Recommendation 1] and [Recommendation 2] to capitalize on identified opportunities and mitigate risks.

### Conclusion
The ${reportParameters.industry} market in ${reportParameters.market} is dynamic and ripe with potential for those who can navigate its complexities effectively.

---
*Generated by Venture Weavers AI on ${new Date().toLocaleDateString()}*
`;
    setGeneratedReportContent(newReportContent);
    // In a real app, you'd save this report to a database
    // For demo, we'll just display it and add to sampleAIReports if needed
  };

  const handleExportReport = () => {
    const blob = new Blob([generatedReportContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportParameters.topic.replace(/\s/g, '-')}-report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleViewReport = (reportId: string) => {
    const report = sampleAIReports.find(r => r.id === reportId);
    if (report) {
      setGeneratedReportContent(report.content);
      setReportParameters(report.parameters);
      setSelectedReportId(reportId);
      setActiveAIReportTab('generate-report'); // Switch to generate tab to show content
    }
  };

  const handleDeleteReport = (reportId: string) => {
    // In a real app, this would delete from the database
    console.log(`Deleting report: ${reportId}`);
    // For demo, we'd filter it out from sampleAIReports if it were mutable state
  };

  return (
    <div className="min-h-screen bg-primary">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">AI Report Development</h1>
          <p className="text-white/80">Generate custom market research and competitive intelligence reports</p>
        </div>

        {/* AI Reports Tabs */}
        <div className="bg-secondary backdrop-blur-sm border border-accent/20 rounded-xl overflow-hidden mb-8">
          <div className="border-b border-accent/20">
            <div className="flex">
              {aiReportsTabs.map((tab) => {
                const IconComponent = tab.icon;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveAIReportTab(tab.id)}
                    className={`flex-1 flex items-center justify-center space-x-2 px-6 py-4 font-medium transition-colors ${
                      activeAIReportTab === tab.id
                        ? 'bg-secondary-light text-white border-b-2 border-highlight'
                        : 'text-white/70 hover:text-white hover:bg-secondary-light'
                    }`}
                  >
                    <IconComponent className="h-4 w-4" />
                    <span>{tab.label}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="p-8">
            {/* Generate AI Report Section */}
            {activeAIReportTab === 'generate-report' && (  
              <div className="space-y-6">
                <h2 className="text-2xl font-bold text-white mb-4">Generate New Report</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-white/70 text-sm mb-2">Industry</label>
                    <select
                      name="industry"
                      value={reportParameters.industry}
                      onChange={handleParameterChange}
                      className="w-full bg-primary border border-accent/20 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-highlight"
                    >
                      <option value="" className="bg-primary-dark">Select Industry</option>
                      <option value="Fintech" className="bg-primary-dark">Fintech</option>
                      <option value="Healthtech" className="bg-primary-dark">Healthtech</option>
                      <option value="E-commerce" className="bg-primary-dark">E-commerce</option>
                      <option value="Edtech" className="bg-primary-dark">Edtech</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-white/70 text-sm mb-2">Market</label>
                    <select
                      name="market"
                      value={reportParameters.market}
                      onChange={handleParameterChange}
                      className="w-full bg-primary border border-accent/20 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-highlight"
                    >
                      <option value="" className="bg-primary-dark">Select Market</option>
                      <option value="UAE" className="bg-primary-dark">UAE</option>
                      <option value="MENA" className="bg-primary-dark">MENA Region</option>
                      <option value="Saudi Arabia" className="bg-primary-dark">Saudi Arabia</option>
                      <option value="Egypt" className="bg-primary-dark">Egypt</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-white/70 text-sm mb-2">Topic</label>
                    <input
                      type="text"
                      name="topic"
                      value={reportParameters.topic}
                      onChange={handleParameterChange}
                      placeholder="e.g., Market Trends, Competitive Analysis"
                      className="w-full bg-primary border border-accent/20 rounded-lg px-3 py-2 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-highlight"
                    />
                  </div>
                  <div>
                    <label className="block text-white/70 text-sm mb-2">Purpose</label>
                    <input
                      type="text"
                      name="purpose"
                      value={reportParameters.purpose}
                      onChange={handleParameterChange}
                      placeholder="e.g., Investment Opportunity Identification"
                      className="w-full bg-primary border border-accent/20 rounded-lg px-3 py-2 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-highlight"
                    />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-white/70 text-sm mb-2">Key Research Elements</label>
                    <textarea
                      name="researchElements"
                      value={reportParameters.researchElements}
                      onChange={handleParameterChange}
                      rows={3}
                      placeholder="e.g., Market size, growth drivers, regulatory environment, key players, emerging technologies"
                      className="w-full bg-primary border border-accent/20 rounded-lg px-3 py-2 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-highlight resize-none"
                    />
                  </div>
                </div>

                {/* Toggle for Advanced Options */}
                <div className="flex items-center justify-between">
                  <button
                    onClick={() => setShowAdvancedOptions(!showAdvancedOptions)}
                    className="flex items-center space-x-2 text-purple-300 hover:text-purple-200 transition-colors"
                  >
                    <Sliders className="h-4 w-4" />
                    <span>{showAdvancedOptions ? 'Hide Advanced Options' : 'Show Advanced Options'}</span>
                  </button>
                </div>

                {/* Advanced Options */}
                {showAdvancedOptions && (
                  <div className="bg-white/5 rounded-lg p-6 space-y-6">
                    <h3 className="text-white font-semibold mb-4">Advanced Report Options</h3>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div>
                        <label className="block text-white/70 text-sm mb-2">Data Visualization</label>
                        <select
                          name="dataVisualization"
                          value={reportParameters.dataVisualization}
                          onChange={handleParameterChange}
                          className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                        >
                          <option value="charts" className="bg-slate-800">Interactive Charts</option>
                          <option value="tables" className="bg-slate-800">Data Tables</option>
                          <option value="infographics" className="bg-slate-800">Infographics</option>
                          <option value="minimal" className="bg-slate-800">Minimal (Text Only)</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-white/70 text-sm mb-2">Analysis Depth</label>
                        <select
                          name="analysisDepth"
                          value={reportParameters.analysisDepth}
                          onChange={handleParameterChange}
                          className="w-full bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                        >
                          <option value="brief" className="bg-slate-800">Brief Overview</option>
                          <option value="standard" className="bg-slate-800">Standard Analysis</option>
                          <option value="comprehensive" className="bg-slate-800">Comprehensive Deep Dive</option>
                          <option value="expert" className="bg-slate-800">Expert-Level Analysis</option>
                        </select>
                      </div>
                    </div>
                    
                    <div className="space-y-3">
                      <div className="flex items-center space-x-2">
                        <input
                          type="checkbox"
                          id="includePredictions"
                          checked={reportParameters.includePredictions}
                          onChange={(e) => handleCheckboxChange('includePredictions', e.target.checked)}
                          className="h-4 w-4 rounded border-white/20 bg-white/10 text-purple-500 focus:ring-purple-500 focus:ring-offset-0"
                        />
                        <label htmlFor="includePredictions" className="text-white/80">
                          Include Market Predictions
                        </label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <input
                          type="checkbox"
                          id="includeRecommendations"
                          checked={reportParameters.includeRecommendations}
                          onChange={(e) => handleCheckboxChange('includeRecommendations', e.target.checked)}
                          className="h-4 w-4 rounded border-white/20 bg-white/10 text-purple-500 focus:ring-purple-500 focus:ring-offset-0"
                        />
                        <label htmlFor="includeRecommendations" className="text-white/80">
                          Include Strategic Recommendations
                        </label>
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-white/70 text-sm mb-2">Custom Sections</label>
                      <div className="flex space-x-2 mb-3">
                        <input
                          type="text"
                          value={reportParameters.customSection}
                          onChange={(e) => setReportParameters(prev => ({ ...prev, customSection: e.target.value }))}
                          placeholder="Add a custom section..."
                          className="flex-1 bg-white/10 border border-white/20 rounded-lg px-3 py-2 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-purple-500"
                        />
                        <button
                          onClick={handleAddCustomSection}
                          className="bg-purple-500 hover:bg-purple-600 text-white px-4 py-2 rounded-lg transition-colors"
                        >
                          Add
                        </button>
                      </div>
                      {reportParameters.customSections.length > 0 && (
                        <div className="flex flex-wrap gap-2 mt-2">
                          {reportParameters.customSections.map((section, index) => (
                            <div 
                              key={index} 
                              className="bg-white/10 text-white/80 px-3 py-1 rounded-full text-sm flex items-center space-x-1"
                            >
                              <span>{section}</span>
                              <button 
                                onClick={() => handleRemoveCustomSection(section)}
                                className="ml-1 text-white/60 hover:text-white"
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                    
                    <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                      <div className="flex items-start space-x-3">
                        <Brain className="h-5 w-5 text-blue-300 mt-0.5" />
                        <div>
                          <h4 className="text-blue-300 font-medium mb-1">AI Report Enhancement</h4>
                          <p className="text-white/80 text-sm">
                            Advanced options allow you to customize the depth, format, and focus of your AI-generated report. 
                            Add custom sections to tailor the report to your specific needs.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                <button
                  onClick={handleGenerateReport}
                  className="bg-gradient-to-r from-accent to-highlight text-white px-6 py-3 rounded-lg font-semibold hover:from-accent-dark hover:to-highlight-dark transition-all duration-300"
                >
                  Generate Report
                </button>

                {generatedReportContent && (
                  <div className="mt-8 bg-primary-dark rounded-lg p-6 border border-accent/20">
                    <h3 className="text-xl font-bold text-white mb-4">Generated Report</h3>
                    <div className="prose prose-invert max-w-none text-white/80 relative">
                      {/* Render markdown content - for a real app, use a markdown renderer */}
                      <pre className="whitespace-pre-wrap font-sans text-sm">
                        {generatedReportContent}
                      </pre>
                      
                      {/* Sample visualization placeholders */}
                      {reportParameters.dataVisualization === 'charts' && (
                        <div className="mt-6 space-y-6">
                          <h4 className="text-white font-semibold">Data Visualizations</h4>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="bg-white/5 rounded-lg p-4">
                              <h5 className="text-white/90 text-sm font-medium mb-2">Market Growth Trends</h5>
                              <div className="h-40 bg-white/10 rounded-lg flex items-center justify-center">
                                <BarChart3 className="h-8 w-8 text-white/40" />
                              </div>
                            </div>
                            <div className="bg-white/5 rounded-lg p-4">
                              <h5 className="text-white/90 text-sm font-medium mb-2">Market Segmentation</h5>
                              <div className="h-40 bg-white/10 rounded-lg flex items-center justify-center">
                                <PieChart className="h-8 w-8 text-white/40" />
                              </div>
                            </div>
                          </div>
                        </div>
                      )}
                      
                      {reportParameters.includePredictions && (
                        <div className="mt-6 bg-white/5 rounded-lg p-4">
                          <h4 className="text-white font-semibold flex items-center space-x-2 mb-3">
                            <Target className="h-5 w-5 text-purple-300" />
                            <span>Market Predictions</span>
                          </h4>
                          <p className="text-white/80 text-sm">
                            Based on current trends and data analysis, we predict significant growth in the {reportParameters.industry} sector within {reportParameters.market} over the next 12-24 months. Key growth drivers include regulatory changes, increased digital adoption, and foreign investment inflows.
                          </p>
                        </div>
                      )}
                      
                      {reportParameters.includeRecommendations && (
                        <div className="mt-6 bg-white/5 rounded-lg p-4">
                          <h4 className="text-white font-semibold flex items-center space-x-2 mb-3">
                            <CheckCircle className="h-5 w-5 text-green-300" />
                            <span>Strategic Recommendations</span>
                          </h4>
                          <ul className="space-y-2 text-white/80 text-sm">
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Focus on {reportParameters.industry === 'Fintech' ? 'embedded finance solutions' : reportParameters.industry === 'Healthtech' ? 'remote patient monitoring' : 'mobile-first experiences'} to capture emerging market opportunities.</span>
                            </li>
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Establish strategic partnerships with local players to navigate regulatory complexities in {reportParameters.market}.</span>
                            </li>
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Invest in data analytics capabilities to gain competitive advantage through customer insights.</span>
                            </li>
                          </ul>
                        </div>
                      )}
                      {/* Sample visualization placeholders */}
                      {reportParameters.dataVisualization === 'charts' && (
                        <div className="mt-6 space-y-6">
                          <h4 className="text-white font-semibold">Data Visualizations</h4>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="bg-white/5 rounded-lg p-4">
                              <h5 className="text-white/90 text-sm font-medium mb-2">Market Growth Trends</h5>
                              <div className="h-40 bg-white/10 rounded-lg flex items-center justify-center">
                                <BarChart3 className="h-8 w-8 text-white/40" />
                              </div>
                            </div>
                            <div className="bg-white/5 rounded-lg p-4">
                              <h5 className="text-white/90 text-sm font-medium mb-2">Market Segmentation</h5>
                              <div className="h-40 bg-white/10 rounded-lg flex items-center justify-center">
                                <PieChart className="h-8 w-8 text-white/40" />
                              </div>
                            </div>
                          </div>
                        </div>
                      )}
                      
                      {reportParameters.includePredictions && (
                        <div className="mt-6 bg-white/5 rounded-lg p-4">
                          <h4 className="text-white font-semibold flex items-center space-x-2 mb-3">
                            <Target className="h-5 w-5 text-purple-300" />
                            <span>Market Predictions</span>
                          </h4>
                          <p className="text-white/80 text-sm">
                            Based on current trends and data analysis, we predict significant growth in the {reportParameters.industry} sector within {reportParameters.market} over the next 12-24 months. Key growth drivers include regulatory changes, increased digital adoption, and foreign investment inflows.
                          </p>
                        </div>
                      )}
                      
                      {reportParameters.includeRecommendations && (
                        <div className="mt-6 bg-white/5 rounded-lg p-4">
                          <h4 className="text-white font-semibold flex items-center space-x-2 mb-3">
                            <CheckCircle className="h-5 w-5 text-green-300" />
                            <span>Strategic Recommendations</span>
                          </h4>
                          <ul className="space-y-2 text-white/80 text-sm">
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Focus on {reportParameters.industry === 'Fintech' ? 'embedded finance solutions' : reportParameters.industry === 'Healthtech' ? 'remote patient monitoring' : 'mobile-first experiences'} to capture emerging market opportunities.</span>
                            </li>
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Establish strategic partnerships with local players to navigate regulatory complexities in {reportParameters.market}.</span>
                            </li>
                            <li className="flex items-start space-x-2">
                              <div className="w-2 h-2 bg-green-400 rounded-full mt-2 flex-shrink-0"></div>
                              <span>Invest in data analytics capabilities to gain competitive advantage through customer insights.</span>
                            </li>
                          </ul>
                        </div>
                      )}
                    </div>
                    <button
                      onClick={handleExportReport}
                      className="mt-6 bg-highlight hover:bg-highlight-dark text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 flex items-center space-x-2"
                    >
                      <Download className="h-5 w-5" />
                      <span>Export Report</span>
                    </button>
                  </div>
                )}
              </div>
            )}

            {/* Reports History Section */}
            {activeAIReportTab === 'reports-history' && (
              <div className="space-y-6">
                <h2 className="text-2xl font-bold text-white mb-4">Reports History</h2>
                {sampleAIReports.length === 0 ? (
                  <div className="text-center py-12">
                    <History className="h-16 w-16 text-white/40 mx-auto mb-4" />
                    <h3 className="text-white font-semibold text-xl mb-2">No reports generated yet</h3>
                    <p className="text-white/70">Generate your first AI report to see it here.</p>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {sampleAIReports.map((report) => (
                      <div key={report.id} className="bg-white/5 border border-white/20 rounded-lg p-6">
                        <h3 className="text-white font-semibold text-lg mb-2">{report.title}</h3>
                        <p className="text-white/70 text-sm mb-4">Generated on {report.date.toLocaleDateString()}</p>
                        <div className="flex flex-wrap items-center gap-3">
                          <button 
                            onClick={() => handleViewReport(report.id)}
                            className="bg-accent hover:bg-accent-dark text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center space-x-2"
                          >
                            <FileText className="h-4 w-4" />
                            <span>View Report</span>
                          </button>
                          <button 
                            onClick={() => handleDeleteReport(report.id)}
                            className="bg-highlight/20 text-highlight hover:bg-highlight/30 px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center space-x-2"
                          >
                            <Trash2 className="h-4 w-4" />
                            <span>Delete</span>
                          </button>
                          <button 
                            className="bg-green-500/20 text-green-300 border border-green-500/30 px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-500/30 transition-colors flex items-center space-x-2"
                          >
                            <Download className="h-4 w-4" />
                            <span>Export</span>
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default AIReportDevelopment;